services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mediapp-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    networks:
      - mediapp-network
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mediapp-backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    networks:
      - mediapp-network
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ENV=production
      - APP_ENV=${APP_ENV:-production}

  database:
    image: postgres:16-alpine
    container_name: mediapp-database
    environment:
      POSTGRES_USER: mediapp_user
      POSTGRES_PASSWORD: mediapp_password_2024
      POSTGRES_DB: mediapp_db
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      db_data_dev: {}
    networks:
      - mediapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediapp_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:community
    container_name: mediapp-sonarqube
    depends_on:
      - database
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://database:5432/mediapp_db
      - SONAR_JDBC_USERNAME=mediapp_user
      - SONAR_JDBC_PASSWORD=mediapp_password_2024
    ports:
      - "9000:9000"
    networks:
      - mediapp-network

volumes:
  db_data:

networks:
  mediapp-network:
    driver: bridge