# Docker Compose v2.39+ configuration for MediApp Development Environment
# Configuración para entorno de desarrollo colaborativo con Supabase

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mediapp-frontend-dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:${APP_PORT:-8080}
    networks:
      - mediapp-network
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package.json

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mediapp-backend-dev
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - ./backend:/app
    environment:
      # Base configuration
      - APP_ENV=${APP_ENV:-development}
      - APP_PORT=${APP_PORT:-8080}
      - APP_DEBUG=${APP_DEBUG:-true}
      
      # Database configuration (Supabase)
      - DATABASE_URL=${DATABASE_URL}
      
      # JWT configuration
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      
      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      
      # API configuration
      - API_VERSION=${API_VERSION:-v1}
      - API_BASE_PATH=${API_BASE_PATH:-/api/v1}
    env_file:
      - .env
    networks:
      - mediapp-network
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - tmp/
            - vendor/
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

networks:
  mediapp-network:
    driver: bridge
    name: mediapp_mediapp-network