name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ BACKEND (Go)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install backend dependencies
        working-directory: backend
        run: go mod tidy

      - name: Build backend
        working-directory: backend/cmd/server
        run: go build -v .

      - name: Test backend with coverage
        id: backend_tests
        working-directory: backend
        run: |
          go test ./... -v -coverprofile=coverage.out
          go tool cover -func=coverage.out | tee coverage.txt
          COV=$(grep total: coverage.txt | awk '{print $3}')
          echo "backend_coverage=$COV" >> $GITHUB_ENV

      # 3️⃣ FRONTEND (Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Test frontend with coverage
        id: frontend_tests
        working-directory: frontend
        run: |
          npm test -- --coverage --watchAll=false
          COV=$(grep 'All files' coverage/lcov-report/index.html | grep -o '[0-9]\+%' | head -n 1)
          echo "frontend_coverage=$COV" >> $GITHUB_ENV

      # 4️⃣ Notificación a Discord (incluye cobertura)
      - name: Notify Discord
        if: always()
        run: |
          STATUS="✅ Build exitoso"
          COLOR=3066993
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="❌ Build falló"
            COLOR=15158332
          fi

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"username\": \"GitHub Actions\",
                 \"embeds\": [{
                   \"title\": \"CI Pipeline - $STATUS\",
                   \"color\": $COLOR,
                   \"fields\": [
                     {\"name\": \"Repositorio\", \"value\": \"${{ github.repository }}\"},
                     {\"name\": \"Branch\", \"value\": \"${{ github.ref_name }}\"},
                     {\"name\": \"Autor\", \"value\": \"${{ github.actor }}\"},
                     {\"name\": \"Cobertura Backend\", \"value\": \"${{ env.backend_coverage }}\"},
                     {\"name\": \"Cobertura Frontend\", \"value\": \"${{ env.frontend_coverage }}\"}
                   ],
                   \"footer\": {\"text\": \"GitHub Actions\"}
                 }]
               }" \
               ${{ secrets.https://discord.com/api/webhooks/1404871267927982140/lZqfdBO3u817OzvQVW9peeBlB3Z6azHw7-fNGKwySQWK7Po0HVTv4WXodwX11QGj2Azx }}
