name: Close sub-issues when parent is closed

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  close_subissues:
    if: |
      github.event.issue != null && github.event.issue.state == 'closed' ||
      github.event.pull_request != null && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Close sub-issues referenced in parent issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue || context.payload.pull_request;
            if (!issue) return;
            const body = issue.body || '';
            const subIssueRegex = /#(\d+)/g;
            const subIssues = [...body.matchAll(subIssueRegex)].map(m => m[1]);
            for (const number of subIssues) {
              const sub = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: Number(number)
              });
              if (sub.data.state !== 'closed') {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: Number(number),
                  state: 'closed'
                });
              }
            }
