# .github/workflows/deploy-staging.yml
name: Deploy to Staging

on:
  push:
    branches:
      - staging # Se activa con cada 'push' a la rama 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authorize GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build and Deploy Backend (Go) to Cloud Run
        id: deploy-backend
        run: |
          # 1. Construir la imagen de contenedor automáticamente (sin Dockerfile)
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend-staging ./backend
          
          # 2. Desplegar el servicio en Cloud Run
          gcloud run deploy backend-staging \
              --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend-staging \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated \
              --set-env-vars=DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Build Frontend (React)
        id: build-frontend
        run: |
          # Obtener la URL del backend recién desplegado
          BACKEND_URL=$(gcloud run services describe backend-staging --platform managed --region us-central1 --format='value(status.url)')
          
          # Ir al directorio del frontend y construir la aplicación
          cd frontend
          npm install
          npm run build
          
          # Configurar la URL de la API en el frontend
          sed -i "s|https://example.com/api|$BACKEND_URL|g" ./build/static/js/*.js
        env:
          REACT_APP_API_URL: "DUMMY_URL" # Esta variable es solo un placeholder, la URL real se inyecta con sed

      - name: Upload to Cloud Storage
        run: |
          # Sube los archivos de la carpeta 'build' del frontend a un bucket
          gsutil -m cp -r ./frontend/build/* gs://${{ secrets.GCP_PROJECT_ID }}-staging-frontend/
          
          # Configura los permisos
          gsutil iam ch allUsers:objectViewer gs://${{ secrets.GCP_PROJECT_ID }}-staging-frontend
          
          # Configura la página de índice
          gsutil web set -m index.html gs://${{ secrets.GCP_PROJECT_ID }}-staging-frontend